all: $(OBJ_DIR)/log.o $(OBJ_DIR)/AsyncLogging.o $(OBJ_DIR)/CountDownLatch.o $(OBJ_DIR)/FileUtil.o $(OBJ_DIR)/LogFile.o $(OBJ_DIR)/LogStream.o
$(OBJ_DIR)/log.o: log.cpp	
	$(CXX) -o $@ -c $<
$(OBJ_DIR)/AsyncLogging.o: AsyncLogging.cpp	
	$(CXX) -o $@ -c $<
$(OBJ_DIR)/CountDownLatch.o: CountDownLatch.cpp	
	$(CXX) -o $@ -c $<
$(OBJ_DIR)/FileUtil.o: FileUtil.cpp	
	$(CXX) -o $@ -c $<
$(OBJ_DIR)/LogFile.o: LogFile.cpp	
	$(CXX) -o $@ -c $<
$(OBJ_DIR)/LogStream.o: LogStream.cpp	
	$(CXX) -o $@ -c $< 

